inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore

Layout/ParameterAlignment:
  Enabled: false

Layout/LineLength:
  Max: 180

Metrics/ClassLength:
  Enabled: true
  Severity: refactor
  Max: 300

Metrics/MethodLength:
  Enabled: true
  Max: 30
  Severity: refactor

Metrics/CyclomaticComplexity:
  Max: 10
  Severity: refactor

Layout/EndAlignment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '{}'

Style/MethodDefParentheses:
  Enabled: false

Naming/PredicateName:
  ForbiddenPrefixes:
    - is_
    - have_

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# breaks using if blocks with assignments
Layout/IndentationWidth:
  Enabled: false

Layout/CaseIndentation:
  EnforcedStyle: end

Style/FormatString:
  Enabled: false

# different methods calls that do exactly the same thing are a smell, regardless of semantics
Style/SignalException:
  EnforcedStyle: only_raise

Style/DoubleNegation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
